config/routes.rb
Rails.application.routes.draw do
  
  resources :games, :players 
  
  root 'games#index'
  
  post '/games/:id' => 'games#simulator'
end

app/models/game.rb
class Game < ActiveRecord::Base
    has_many :players, dependent: :destroy
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    include Simulate
    
    def index
        @session = Game.new
        @session.save
    
        #pull id from newly created created object and use it to link form to new game
        @id = @session.id
    end
    
    def show
        @players = Player.where(:game_id => fetch)
        
        @living = simulate(@players)
        
        if simulate(@players).length == 1
            game = Game.where(:id => fetch)
            game.each do |g|
                g.destroy 
            end
            @done = true
        end
    end
    
    def simulator
        @alert = false
        
        unless params[:player] == nil
            @game_id = fetch
        
            @all = Player.where(:game_id => @game_id)
            @name = params[:player][:name]
            
            if check(@name, @all)
                #new player's score is determined using parameters on games#simulator
                @player = Player.new
                @player.game_id = @game_id
                @player.name = params[:player][:name]
                
                if params[:player][:age].to_i >=30
                    @player.score -= 5
                else
                    @player.score +=2
                end
                
                case params[:skill]
                
                when "1"
                    @player.score += 5
                when "2"
                    @player.score += 5
                when "3"
                    @player.score += 10
                when "4"
                    @player.score -= 5
                end
                
                case params[:kindness]
                
                when "1"
                    @player.score -= 1
                when "3"
                    @player.score += 3
                when "4"
                    @player.score += 5
                when "5"
                    @player.score -= 1
                end
                
                @player.score = params[:improvise].to_i + 4
                @player.score = params[:combat].to_i - 1
                @player.score = params[:sociability].to_i - 1
                @player.score = params[:emotions].to_i + 4
                @player.score = params[:intelligence].to_i + 3
                @player.score = params[:strength].to_i + 3
                
                @player.save
                
                
            else
                @alert = true
            end
            
            #initialize new variable with added players
            @every_player = Player.where(:game_id => @game_id)
        end
    end
    
    private
    
        def fetch
            url = request.path_parameters
            return url[:id]
        end
        
        def check(name, players)
        #iterates through all players checking for duplicates
        #return values used to determine if duplicate exists
        #if return true -> duplicate exists
        #else -> duplicate does not exist
            players.each do |p|
                if name.downcase == p.name.downcase
                    return false
                else
                    return true
                end
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/simulate.rb
module Simulate
    
    #function used to determine which players are alive and dead
    #players is an array
    #breaks players down into groups of 2 and pits them against each other
    def simulate(players)
        living = []
        
        @factor = 0
        
        #used to break down odd numbers
        if players.length % 2 == 1
            survivor = players[players.length - 1]
            living << survivor
        end
        
        for i in 0...(players.length/2)
            a = players[@factor]; @factor += 1
            b = players[@factor]; @factor += 1

            if a.score >= b.score
                b.destroy
                living << a
            else
                a.destroy
                living << b
            end
            
            i += 1
        end 
        
        return living
    end
end

app/views/games/index.html.erb
<h1 id="title" class="text-center">TAMPER</h1>
<div class="row text-center" id="begin">
    <h3 id="intro">At Ridgewood High School in Ridgewood NJ, in 2015, the sophomore AP US History class had a hypothetical discussion regarding which Ridgewood High School student would best survive in an anarchic, post-apocalyptic world. As a solution, TAMPER was born. TAMPER is a battle simulator that determines who out of a group of participants would most likely survive in a world similar to the one Suzanne Collins illustrates in "The Hunger Games." Using an advanced algorithm that assesses participants based on their emotional and physical attributes, TAMPER accurately selects the strongest of all candidates and names them the victor. Enjoy facing off against friends, family, and enemies on the battlefield</h3>
    <!--form used to initiate new game-->
    <%=form_for :games, url: game_path(:id => @id) do |f|%>
        <%=f.submit 'Join the Game', class: 'btn btn-default', style: 'border-radius: 100px; font-size: 25px;'%>
    <%end%>
</div>

app/views/games/show.html.erb
<div class="row text-center">
    <div class="col-lg-6">
        <%=image_tag "map.png", class: 'img-circle', id: 'map'%>
        <!--open script tag and initialize new field class-->
    </div>
    <div class="col-lg-6">
        <h1>Living Players:</h1>
        <br>
        <ul id="living">
        <%@living.each do |l|%>
                <li><%=l.name%></li>
        <%end%>
        </ul>
        <%if @done%>
            <%=link_to 'New Game', games_path, class: 'btn btn-default'%>
        <%else%>
            <%=link_to 'Next Round', game_path, class: 'btn btn-default'%>
        <%end%>
    </div>
</div>
<div class="row text-center">
    <!--newsreel-->
    <!--animate using jquery and jquery animations-->
</div>

app/views/games/simulator.html.erb
<div class="row text-center">
    <h1>Define Opponents</h1>
</div>

<div>
    <%if @alert%>
        <script>
            $(document).ready(function(){
               alert("The character you created already exists. Please add a new character"); 
            });
        </script>
    <%end%>
</div>

<div class="container">
    <div class="col-lg-6">
        <!--form used to add new players to existing game-->
        <%=form_for :player, url: game_path do |f|%>
            <%=f.label 'name'%><br>
            <%=f.text_field :name, value: 'Primrose Everdeen'%><br>
            <%=f.label 'age'%><br>
            <%=f.text_field :age, value: '12'%><br>
            <%=f.label 'special skill'%><br>
            <%=select_tag :skill, options_for_select([['combat', 1], ['camouflage', 2], ['survival', 3], ['none', 4]])%><br>
            <%=f.label 'Ability to Improvise'%><br>
            <%=select_tag :improvise, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.label 'Combat Skills'%><br>
            <%=select_tag :combat, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.label 'sociability'%><br>
            <%=select_tag :sociability, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.label 'Kindness'%><br>
            <%=select_tag :kindness, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.label 'Physical Strength'%><br>
            <%=select_tag :strength, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.label 'Emotional Endurance'%><br>
            <%=select_tag :emotions, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.label 'Intelligence'%><br>
            <%=select_tag :intelligence, options_for_select([[1], [2], [3], [4], [5]])%><br>
            <%=f.submit 'Add Player', class: 'btn btn-default'%>
        <%end%>
        <%=link_to 'Run Simulator', game_path, class: 'btn btn-default'%>
    </div>
    <div class="col-lg-6" id="players_column">
        <h1>Players:</h1>
        <%if @every_player != nil%>
            <%@every_player.each do |a|%>
                <p><%=a.name%></p>
                
            <%end%>
        <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TAMPER</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--bootstrap-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%=csrf_meta_tags%>
  <meta name="author" content="Christian Sermetis">
  <meta name="keywords" content="alive, dead, battle, TAMPER">
  <%=Gon::Base.render_data%>
</head>
<body>
  <div class="wrapper">
    <%= yield %>
  </div>
  <footer class="text-center" id="contact">
        <p>TAMPER is an open-source project developed by Christian Seremetis, click <a href="https://github.com/cseremetis/hgsimulator">here</a> to see the source code</p>
  </footer>
</body>
</html>